spring:
  application:
    name: document-repo
  profiles:
    active: dev
  jackson:
    serialization:
      fail-on-empty-beans: false
      indent-output: true
      close-closeable: true
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false  
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:mysql://localhost:3306/document-repo
    username: root
    password: root
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update  # Options: none, validate, update, create, create-drop
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true  
  sql:
    init:
      mode: never   # always, embedded
      continue-on-error: false
      schema-locations: classpath:/data/schema.mysql
      data-locations: classpath:/data/data.mysql
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    port: 587  #589
    username: otienogordon95@gmail.com
    password: Otieno@95
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
    verify:
      host: http://localhost:8085 #${VERIFY_EMAIL_HOST}
server:
  port: 8085 
  error:
    path: /user/error
    whitelabel:
      enabled: true