#POSTGRESQL_USERNAME: postgres
#POSTGRESQL_PASSWORD: test123
#POSTGRESQL_HOST: 172.31.0.2
#POSTGRESQL_PORT: 5432
#POSTGRESQL_DATABASE: document_db

#server
#CONTAINER_PORT: 8085
ACTIVE_PROFILE: dev

#Email config
EMAIL_HOST: smpt.gmail.com
EMAIL_PORT: 589
EMAIL_ID: otienogordon95@gmail.com
EMAIL_PASSWORD: Otieno@95
VERIFY_EMAIL_HOST: http://localhost:8085
